apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: niquoumouq
        image: quay.io/fedora/httpd-24
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    tier: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP

---

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: niqoumouq-ingress
  namespace: nexus9111-dev
spec:
  host: niqoumouq.apps.rm3.7wse.p1.openshiftapps.com
  to:
    kind: Service
    name: frontend-service
    weight: 100
  port:
    targetPort: 80-tcp
  wildcardPolicy: None
