name: Déployer sur OpenShift

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code source
        uses: actions/checkout@v3

      - name: Install oc
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar xzf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Connect to openshift
        run: |
          oc login ${{ secrets.OPENSHIFT_SERVER }} --token=${{ secrets.OPENSHIFT_TOKEN }}

      - name: Déployer l'image Nginx
        run: |
          oc apply -f kube/front.yaml 